[build]
  functions = "functions"
  publish = "ui/webapp"
  command = "netlify-lambda build functions-source"


[[redirects]]
  from = "/catalog/Authors"
  to = "/.netlify/functions/server3/Authors"
  status = 200
  force = true

[[redirects]]
  from = "/catalog/Books"
  to = "/.netlify/functions/server3/Books"
  status = 200
  force = true

[[redirects]]
  from = "/catalog/$metadata"
  to = "/.netlify/functions/server3/$metadata"
  status = 200
  force = true